replicaCount: 1

image:
  repository: go-hello-registry:5000/kkolcz/my-go-rest-foundation
  pullPolicy: IfNotPresent
  tag: "0.1.4"

service:
  type: ClusterIP
  port: 80

app:
  env:
    - name: APP_ENV
      value: "dev"
    - name: HTTP_PORT
      value: "8080"