replicaCount: 1

image:
  # repository: kkolcz/go-hello
  repository: go-hello-registry:5000/kkolcz/go-hello
  pullPolicy: IfNotPresent
  tag: "0.1.1"

service:
  type: ClusterIP
  port: 80

app:
  name: go-hello
  env:
    - name: APP_NAME
      value: "go-hello-from-helm"